config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  %w(about).each do |page|
    get page, to: "pages##{page}", as: page
  end

  get "contact", to: "messages#new", as: :contact
  resources :messages, only: [:create, :new]

end

app/models/message.rb
class Message
  include ActiveModel::Model

  attr_accessor :fname, :lname, :email, :phone, :msg

  validates :fname, presence: true
  validates :lname, presence: true
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates :msg, presence: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   # Prevent CSRF attacks by raising an exception.
   # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      notif_admin_about_new_message(@message)
      redirect_to new_message_path, notice: "Your message has been sent."
    else
      render :new
    end
  end

  def notif_admin_about_new_message(message)
    MessageMailer.new_message(message).deliver_now
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def render_flash_messages
    msg = nil
    class_name = nil
    [:notice, :success, :alert].each do |key|
      next if flash[key].blank?
      msg = flash[key]
      class_name = key
      class_name = :success if %w(notice success).include?(key.to_s)
      break
    end
    return if msg.blank?
    close_link = link_to("x", "#", class: "close")
    msg.blank? ? "" : content_tag(:div, "#{close_link}#{msg}".html_safe, :class => "alert alert-#{class_name}", "data-dismiss" => "alert")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="footer-wrapper">
    <div class="row">
      <div class="col-sm-4 col-xs-12 col-md-4 col-lg-4">
        <div class="footerWidget">
          <%= link_to image_tag("logo.png", class: "footer-image"), root_path %>
          <p>Description text</p>
        </div>
      </div>
      <div class="col-md-4 col-xs-12 col-lg-4 col-sm-4">
        <div class="footerWidget footer-contact">
          <h3>Contact info</h3>
          <p>
          <i class="fa fa-map-marker"></i>&nbsp;Augusta Cesarca 8, Cacinci<br>
          <i class="fa fa-globe"></i>&nbsp;Republic of Croatia <br>
          <i class="fa fa-mobile"></i>&nbsp;+385 989304585<br>
          <a href="mailto:matijaramic@gmail.com"><i class="fa fa-envelope"></i>matijaramic@gmail.com</a>
          </p>
        </div>
      </div>
      <div class="col-md-4 col-xs-12 col-lg-4 col-sm-4">
        <div class="articles">
          <h3>Latest  blog posts</h3>
          <ul class="list-unstyled iconList borderList">
            <li><%= link_to "ovo je naslov prvog članka" %></li>
            <li><%= link_to "naslov drugog članka" %></li>
            <li><%= link_to "naslov trećeg članka" %></li>
            <li><%= link_to "Još jedan naslov" %></li>
            <li><%= link_to "zadnji naslov članka" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="footerBottom">
    <div class="footer-wrapper-bottom">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <p>Copyright © 2015 <%= link_to "Ramić", root_path %> | All rights reserved.</p>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_header.html.erb
<div id="header">
  <div class="navbar" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
        <span class="sr-only visible-xs">Toggle navigation</span>
        <i class="glyphicon glyphicon-menu-hamburger"></i>
      </button>
    </div>
    <div class="navbar-collapse collapse sidebar-navbar-collapse">
      <%= link_to image_tag("logo.png", class: "logo-image hidden-xs"), root_path %>
      <ul class="nav navbar-nav navbar-right">
        <li>Work</li>
        <li><%= link_to "About", about_path %></li>
        <li>Blog</li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'admin', media: 'all' %>
  <%= javascript_include_tag 'admin' %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Lato:400,700,900,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light+Two&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

</head>
<body>


<%= render_flash_messages %>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Lato:400,700,900,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light+Two&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

</head>
<body>

<%= render 'layouts/header'%>

<%= render_flash_messages %>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/messages/_form.html.erb
<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="well well-sm">
      <%= simple_form_for @message, method: :post, defaults: { label: false }, html: { class: 'form-horizontal' } do |f| %>
        <fieldset>
          <legend class="text-center header">Contact me now!</legend>

          <div class="form-group">
            <span class="col-md-1 col-md-offset-2"><i class="fa fa-user fa-3x"></i></span>
            <div class="col-lg-8 col-md-8">
              <%= f.input :fname, placeholder: "First Name" %>
            </div>
          </div>
          <div class="form-group">
            <span class="col-md-1 col-md-offset-2"><i class="fa fa-user fa-3x"></i></span>
            <div class="col-lg-8 col-md-8">
              <%= f.input :lname, placeholder: "Last Name" %>
            </div>
          </div>

          <div class="form-group">
            <span class="col-md-1 col-md-offset-2"><i class="fa fa-envelope fa-3x"></i></span>
            <div class="col-lg-8 col-md-8">
              <%= f.input :email, placeholder: "Email Address" %>
            </div>
          </div>

          <div class="form-group">
            <span class="col-md-1 col-md-offset-2"><i class="fa fa-phone-square fa-3x"></i></span>
            <div class="col-lg-8 col-md-8">
              <%= f.input :phone, placeholder: "Phone" %>
            </div>
          </div>

          <div class="form-group">
            <span class="col-md-1 col-md-offset-2"><i class="fa fa-pencil-square fa-3x"></i></span>
            <div class="col-lg-8 col-md-8">
              <%= f.input :msg, input_html: { rows: 10 }, as: :text, placeholder: "Enter your message here." %>
            </div>
          </div>

          <div class="form-group text-center">
            <div class="col-lg-12 col-md-12">
              <%= f.button :submit, "Send Message", class: "btn btn-primary btn-lg" %>
            </div>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/new.html.erb
<div id="contact">
  <div class="contact-wrapper">
    <%= render 'messages/form' %>
  </div>
</div>
<%= render 'pages/social' %>

app/views/pages/_form.html.erb
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="well well-sm">
        <%= simple_form_for :message, defaults: { label: false }, html: { class: 'form-horizontal' } do |f| %>
          <fieldset>
            <legend class="text-center header">Contact me now!</legend>

            <div class="form-group">
              <span class="col-md-1 col-md-offset-2"><i class="fa fa-user fa-3x"></i></span>
              <div class="col-lg-8 col-md-8">
                <%= f.input :fname, placeholder: "First Name" %>
              </div>
            </div>
            <div class="form-group">
              <span class="col-md-1 col-md-offset-2"><i class="fa fa-user fa-3x"></i></span>
              <div class="col-lg-8 col-md-8">
                <%= f.input :lname, placeholder: "Last Name" %>
              </div>
            </div>

            <div class="form-group">
              <span class="col-md-1 col-md-offset-2"><i class="fa fa-envelope fa-3x"></i></span>
              <div class="col-lg-8 col-md-8">
                <%= f.input :email, placeholder: "Email Address" %>
              </div>
            </div>

            <div class="form-group">
              <span class="col-md-1 col-md-offset-2"><i class="fa fa-phone-square fa-3x"></i></span>
              <div class="col-lg-8 col-md-8">
                <%= f.input :phone, placeholder: "Phone" %>
              </div>
            </div>

            <div class="form-group">
              <span class="col-md-1 col-md-offset-2"><i class="fa fa-pencil-square fa-3x"></i></span>
              <div class="col-lg-8 col-md-8">
                <%= f.input :msg, input_html: { rows: 10 }, as: :text, placeholder: "Enter your message here." %>
              </div>
            </div>

            <div class="form-group text-center">
              <div class="col-lg-12 col-md-12">
                <%= f.button :submit, "Send Message", class: "btn btn-primary btn-lg" %>
              </div>
            </div>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>

app/views/pages/_social.html.erb
<div class="social-wrapper">
  <h1 class="social-title">I'm around the web!</h1>
  <ul>
    <li><%= link_to "", "https://www.facebook.com/matija.ramic", class: "fa fa-facebook fa-2x" %></li>
    <li><%= link_to "", "https://twitter.com/matijaramic", class: "fa fa-twitter fa-2x" %></li>
    <li><%= link_to "", "https://www.linkedin.com/profile/view?id=AAIAABNpgBUBsTvMIF8yJqPaNeZGA4Gndt7mp30&trk=nav_responsive_tab_profile", class: "fa fa-linkedin fa-2x" %></li>
    <li><%= link_to "", "https://plus.google.com/u/0/108218836763937110805/posts", class: "fa fa-google-plus fa-2x" %></li>
    <li><a href="mailto:matijaramic@gmail.com"><i class="fa fa-envelope-o fa-2x"></i></a></li>
  </ul>
</div>
<div class="social-share">
  <h1>Clean Social Share Buttons for Blogs</h1>
  <div id="twitter" data-url="http://mattaxell.com/"></div>
  <div id="facebook" data-url="http://mattaxell.com/"></div>
  <div id="pinterest" data-url="http://mattaxell.com/"></div>
</div>

app/views/pages/about.html.erb
<div id="about">
  <div class="about-wrapper">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h1>About Me</h1>
        <%= image_tag("user.png", class: "image") %>
        <div class="intro-text">
          <div class="name"><h1 class="title">Hi, I am Matija Ramić</h1></div>
          <p>Lorem ipsum dolor sit amet, exerci vituperata mediocritatem ad pri, an semper placerat menandri sit. <br>Ex cum nobis putent, et vis velit iudico eripuit. Per at case solet insolens. Et aliquid commune quo,<br> iriure definiebas efficiantur pri an. Vis no atqui essent voluptatum, eu nostrum singulis recteque vix.<br> Ferri accumsan appetere nec no, te cum liber scaevola evertitur.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="process">
  <h2>Process</h2>
  <div class="process-wrapper">
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="process-content">
          <i class="fa fa-flask"></i>
          <p>Research</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="process-content">
          <i class="fa fa-pencil-square-o"></i>
          <p>Design</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="process-content">
          <i class="fa fa-code"></i>
          <p>Develop</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="process-content">
          <i class="fa fa-rocket"></i>
          <p>Deploy</p>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'pages/skills/skills' %>

app/views/pages/index.html.erb
<div id="home">
  <div class="home-content">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <%= image_tag("user.png", class: "image") %>
        <div class="intro-text">
          <div class="name"><h1 class="title">Hi, I am Matija Ramić</h1></div>
          <p>Lorem ipsum dolor sit amet, exerci vituperata mediocritatem ad pri, an semper placerat menandri sit. <br>Ex cum nobis putent, et vis velit iudico eripuit. Per at case solet insolens. Et aliquid commune quo,<br> iriure definiebas efficiantur pri an. Vis no atqui essent voluptatum, eu nostrum singulis recteque vix.<br> Ferri accumsan appetere nec no, te cum liber scaevola evertitur.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="home-content">
  <h3>What I do</h3>
  <p class="description">I am passionate about combining function, interaction and form <br>
  to design for fitting user experiences that make people happy.</p>
  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
      <div class="column-content">
      <%= image_tag("ruby.png", class: "content-image") %>
      <h2>RoR development</h2>
      <p>Lorem ipsum dolor sit amet, reque vivendum cotidieque quo at. Te invidunt accusata adversarium vix, ius enim velit ne. Est mazim aeque cetero in, tota dicunt in sea, pri homero accusamus at. Cu cibo expetenda pro, pri te integre meliore interesset.
      </p>
      </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
      <div class="column-content">
      <%= image_tag("webresponsive.jpg", class: "content-image") %>
      <h2>Responsive design</h2>
      <p>Lorem ipsum dolor sit amet, reque vivendum cotidieque quo at. Te invidunt accusata adversarium vix, ius enim velit ne. Est mazim aeque cetero in, tota dicunt in sea, pri homero accusamus at. Cu cibo expetenda pro, pri te integre meliore interesset.
      </p>
    </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
      <div class="column-content">
      <%= image_tag("design.png", class: "content-image") %>
      <h2>First class design</h2>
      <p>Lorem ipsum dolor sit amet, reque vivendum cotidieque quo at. Te invidunt accusata adversarium vix, ius enim velit ne. Est mazim aeque cetero in, tota dicunt in sea, pri homero accusamus at. Cu cibo expetenda pro, pri te integre meliore interesset.
      </p>
      </div>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
      <div class="column-content">
      <%= image_tag("browserfrendly.png", class: "content-image") %>
      <h2>Browser frendly</h2>
      <p>Lorem ipsum dolor sit amet, reque vivendum cotidieque quo at. Te invidunt accusata adversarium vix, ius enim velit ne. Est mazim aeque cetero in, tota dicunt in sea, pri homero accusamus at. Cu cibo expetenda pro, pri te integre meliore interesset.
      </p>
    </div>
    </div>
  </div>
</div>
<%= render 'pages/social' %>

app/views/pages/skills/_skill1.html.erb
<div class="circle-wrap">
  <div class="circle">
    <div class="mask full">
      <div class="fill"></div>
    </div>
    <div class="mask half">
      <div class="fill"></div>
    </div>
  </div>
  <div class="inside-circle">
    50%
  </div>
</div>
<p>Ruby on Rails</p>

app/views/pages/skills/_skill2.html.erb
<div class="circle-wrap">
  <div class="circle">
    <div class="mask full">
      <div class="fill"></div>
    </div>
    <div class="mask half">
      <div class="fill"></div>
    </div>
  </div>
  <div class="inside-circle">
    50%
  </div>
</div>
<p>Photoshop</p>

app/views/pages/skills/_skill3.html.erb
<div class="circle-wrap3">
  <div class="circle3">
    <div class="mask3 full3">
      <div class="fill3"></div>
    </div>
    <div class="mask3 half3">
      <div class="fill3"></div>
    </div>
  </div>
  <div class="inside-circle3">
    90%
  </div>
</div>
<p>Html</p>

app/views/pages/skills/_skill4.html.erb
<div class="circle-wrap4">
  <div class="circle4">
    <div class="mask4 full4">
      <div class="fill4"></div>
    </div>
    <div class="mask4 half4">
      <div class="fill4"></div>
    </div>
  </div>
  <div class="inside-circle4">
    70%
  </div>
</div>
<p>css</p>

app/views/pages/skills/_skills.html.erb
<div id="skills">
  <div class="skills-wrapper">
    <h1>My Skills</h1>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <%= render 'pages/skills/skill1' %>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <%= render 'pages/skills/skill2' %>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <%= render 'pages/skills/skill3' %>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <%= render 'pages/skills/skill4' %>
      </div>
    </div>
  </div>
</div>